# Generated by Django 3.1.4 on 2021-01-13 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('no_of_views', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.TextField()),
                ('password', models.TextField(max_length=15)),
                ('status', models.TextField(max_length=250)),
                ('profile_pic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvote', to='posts.post')),
                ('userId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='upvote', to='posts.user')),
            ],
        ),
        migrations.CreateModel(
            name='TopicFollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='posts.user')),
                ('topicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followedTopic', to='posts.topic')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postImage', to='posts.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to='posts.user'),
        ),
        migrations.CreateModel(
            name='FollowersFollowings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='posts.user')),
                ('followingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='posts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Downvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downvote', to='posts.post')),
                ('userId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='downvote', to='posts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Contains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contains', to='posts.post')),
                ('topicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contains', to='posts.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('no_of_up', models.PositiveIntegerField(default=0)),
                ('no_of_down', models.PositiveIntegerField(default=0)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_post', to='posts.post')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentAuthor', to='posts.user')),
            ],
        ),
    ]
