# Generated by Django 3.1.4 on 2021-01-13 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('type', models.TextField()),
                ('postId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_post', to='posts.post')),
                ('reciever_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieving_user', to='posts.user')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_user', to='posts.user')),
            ],
        ),
    ]
