# Generated by Django 3.1.4 on 2021-01-07 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(upload_to=''),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('no_of_up', models.PositiveIntegerField(default=0)),
                ('no_of_down', models.PositiveIntegerField(default=0)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_post', to='posts.user')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentAuthor', to='posts.user')),
            ],
        ),
    ]
