# Generated by Django 3.1.4 on 2021-01-13 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='postId',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_post', to='posts.post'),
        ),
    ]
