# Generated by Django 3.1.4 on 2020-12-29 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201229_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followings',
            name='followingId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='posts.user'),
        ),
        migrations.AlterField(
            model_name='followings',
            name='topicId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='posts.topic'),
        ),
    ]
