# Generated by Django 3.1.4 on 2020-12-29 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201229_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowersFollowings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='posts.user')),
                ('followingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='posts.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='followings',
            name='followingId',
        ),
        migrations.RemoveField(
            model_name='followings',
            name='topicId',
        ),
        migrations.RemoveField(
            model_name='followings',
            name='userId',
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
        migrations.DeleteModel(
            name='Followings',
        ),
    ]
