# Generated by Django 3.1.4 on 2020-12-31 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20201229_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicFollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='posts.user')),
                ('topicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followedTopic', to='posts.topic')),
            ],
        ),
    ]
